// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Locally the Neon direct endpoint may be suspended while the pooler stays
  // live — use DATABASE_URL (pooled) for migrations in dev. In production
  // (Vercel) set DIRECT_URL to the non-pooled connection string.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
